name       : qt5ct
version    : '0.39'
release    : 5
source     :
    - https://sourceforge.net/projects/qt5ct/files/qt5ct-0.39.tar.bz2/download : 3769ecdcbdf821d52f7f1e013531a9692c28bab0bae5f133d22cba7702333e19
license    : BSD-2-Clause
component  : desktop.qt
summary    : This program allows users to configure Qt5 settings (theme, font, icons,
    etc.) under DE/WM without Qt integration.
description: |
    This program allows users to configure Qt5 settings (theme, font, icons, etc.) under DE/WM without Qt integration.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
