name       : qt5ct
version    : 0.36
release    : 3
source     :
    - https://sourceforge.net/projects/qt5ct/files/qt5ct-0.36.tar.bz2/download : 8fc3942f34d377af5533a0953cca633a7babc60c0476fd4318b617702183ee89
license    : BSD-2-Clause
component  : desktop.qt
summary    : This program allows users to configure Qt5 settings (theme, font, icons,
    etc.) under DE/WM without Qt integration.
description: |
    This program allows users to configure Qt5 settings (theme, font, icons, etc.) under DE/WM without Qt integration.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
